version: '3.3'

services:
  consumer:
    container_name: data-history-consumer
    build:
      context: .
      dockerfile: DockerfileConsumer

  server:
    container_name: data-history-server
    build:
      context: .
      dockerfile: DockerfileServer
    ports:
      - "9090:9090"