spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DATABASE_URI}
    username: ${DATABASE_USER}
    password: ${DATABASE_PWD}

module:
  history:
    host: ${HISTORY_MODULE_SERVER}