spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DATABASE_URI}
    username: ${DATABASE_USER}
    password: ${DATABASE_PWD}
  kafka:
    producer:
      client-id: web-application-producer
    bootstrap-servers: ${KAFKA_SERVER}

module:
  history:
    host: ${HISTORY_MODULE_SERVER}