
version: "2"

services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    container_name: smart-home-zookeeper
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - "zookeeper_data:/bitnami"
    
  kafka:
    image: 'bitnami/kafka:latest'
    container_name: smart-home-kafka
    ports:
      - "9093:9093"
    environment:
      - KAFKA_HEAP_OPTS=-Xmx1024m -Xms1024m
      - KAFKA_BROKER_ID=1
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=false
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://0.0.0.0:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://smart-home-kafka:9092,EXTERNAL://139.59.170.253:9093
      - KAFKA_CFG_ZOOKEEPER_CONNECT=smart-home-zookeeper:2181
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
    depends_on:
      - zookeeper
    volumes:
      - "kafka_data:/bitnami"


volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
