
version: "2"

services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    container_name: smart-home-zookeeper
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - "zookeeper_data:/bitnami"
    
  kafka:
    image: 'bitnami/kafka:latest'
    container_name: smart-home-kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=smart-home-zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=false
    depends_on:
      - zookeeper
    volumes:
      - "kafka_data:/bitnami"


volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
