spring:
  kafka:
    consumer:
      auto-offset-reset: earliest
      client-id: smart-home-modules
      group-id: last-state-module
    bootstrap-servers: ${KAFKA_SERVER}
  data:
    mongodb:
      uri: ${CONNECTION_URI}

server:
  port: 8083

consumer:
  topics:
    - hubs-messages